/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './layouts/**/*.html',
    './content/**/*.{html,md}',
    './assets/css/**/*.css',
  ],
  theme: {
    extend: {
      colors: {
        darkTheme: '#111827',
        brand: {
          DEFAULT: '#0B162C',
          muted: '#334155',
        },
      },
      animation: {
        marquee: 'marquee 25s linear infinite',
        'scroll-up': 'scroll-up 35s linear infinite',
        'scroll-down': 'scroll-down 35s linear infinite',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'scroll-up': {
          '0%': { transform: 'translateY(0)' },
          '100%': { transform: 'translateY(-50%)' },
        },
        'scroll-down': {
          '0%': { transform: 'translateY(-50%)' },
          '100%': { transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
  safelist: [
    'animate-marquee',
    'animate-scroll-up',
    'animate-scroll-down',
    'group-hover:[animation-play-state:paused]',
    'snap-none',
    'animate-bounce',
    'text-brand',
    'hover:text-brand',
    'bg-brand',
    'nav-shell',
    'nav-item-browse',
    'nav-item-about',
    'nav-dropdown',
    'nav-dropdown--mega',
    'nav-dropdown--about',
    'is-open',
    'group-hover/browse:rotate-180',
    'group-hover/browse:opacity-100',
    'group-hover/browse:visible',
    'group-hover/browse:pointer-events-auto',
    'group-focus-within/browse:opacity-100',
    'group-focus-within/browse:visible',
    'group-focus-within/browse:pointer-events-auto',
    'group-hover/about:rotate-180',
    'group-hover/about:opacity-100',
    'group-hover/about:visible',
    'group-hover/about:pointer-events-auto',
    'group-focus-within/about:opacity-100',
    'group-focus-within/about:visible',
    'group-focus-within/about:pointer-events-auto',
    'group-hover/cat:text-brand',
    'group-hover/cat:bg-brand/10',
    'line-clamp-1',
    'search-palette-open',
    'mobile-menu-open',
    'search-palette--embedded',
    'is-visible',
    'is-active',
    'after:absolute',
    'after:inset-0',
    'after:rounded-2xl',
    'after:z-10',
    "after:content-['']",
    'search-palette__badge--ai',
    'search-palette__badge--game',
    'search-palette__badge--design',
    'search-palette__badge--store',
    'nav-mega',
    'nav-mega__panel',
    'nav-mega__grid',
    'nav-mega__col',
    'nav-mega__col--hubs',
    'nav-mega__label',
    'nav-mega__list',
    'nav-mega__list--hubs',
    'nav-mega__cat-link',
    'nav-mega__cat-icon',
    'nav-mega__cat-text',
    'nav-mega__cat-name',
    'nav-mega__cat-sub',
    'nav-mega__cat-arrow',
    'nav-mega__hub-link',
    'nav-mega__view-all',
    'theme-toggle-nav',
    'theme-toggle-nav__icon',
    'theme-toggle-nav__icon--dark',
    'theme-toggle-nav__icon--light',
    'theme-toggle-nav__icon--glass',
    'theme-toggle-nav__glyph',
    'browse-index',
    'browse-index__hero',
    'browse-category-card',
    'browse-category-grid',
    'browse-hub-card',
    'browse-hub-grid',
    'home-why',
    'home-why__header',
    'home-why__hero',
    'home-why__hero-inner',
    'home-why__grid',
    'home-why__title',
    'home-why__intro',
    'home-why__card',
    'home-why__card-title',
    'home-why__card-text',
    'home-why__perks',
    'home-why__perk',
    'home-why__perk-icon',
    'home-why__perk-text',
    'contact-form-card',
    'contact-link',
    'contact-submit',
    'contact-field__input',
    'contact-page',
    'contact-layout',
  ],
};
